-- TEST DATA FOR same_stations_diff_stops()

INSERT INTO ROUTE_STATIONS VALUES(1, True, 1, 25, null);
INSERT INTO ROUTE_STATIONS VALUES(2, False, 2, 25, 1);
INSERT INTO ROUTE_STATIONS VALUES(3, False, 3, 25, 2);
INSERT INTO ROUTE_STATIONS VALUES(4, False, 4, 25, 3);
INSERT INTO ROUTE_STATIONS VALUES(5, True, 5, 25, 4);
INSERT INTO ROUTE_STATIONS VALUES(6, False, 6, 25, 5);
INSERT INTO ROUTE_STATIONS VALUES(7, True, 7, 25, 6);
INSERT INTO ROUTE_STATIONS VALUES(8, False, 8, 25, 7);
INSERT INTO ROUTE_STATIONS VALUES(9, True, 9, 25, 8);
INSERT INTO ROUTE_STATIONS VALUES(10, True, 10, 25, 9);
